In [4]:
import numpy as np
import pybobyqa

In [19]:
def f(v):
    [x,y,z] = v
    a = 1
    b = 100
    return (a-x)**2 + b*(y-x**2)**2 + z

lower = np.array([-10.0, -10.0,-10.0])
upper = np.array([0.9, 0.85, 1])


In [20]:
soln = pybobyqa.solve(f, np.array([0.0,0.0,0.0]), bounds = (lower,upper))

In [21]:
print(soln)

****** Py-BOBYQA Results ******
Solution xmin = [  0.9    0.81 -10.  ]
Objective value f(xmin) = -9.99
Needed 141 objective evaluations (at 141 points)
Approximate gradient = [ -1.99999862e-01  -3.83573965e-19   9.99999969e-01]
Approximate Hessian = [[ 665.38750237 -362.50316677    4.25279138]
 [-362.50316677  205.26790144   17.81488663]
 [   4.25279138   17.81488663   12.40984539]]
Exit flag = 0
Success: rho has reached rhoend
******************************



In [26]:
list(slice(-4,4,0.25))

TypeError: 'slice' object is not iterable

In [23]:
>>> params = (2, 3, 7, 8, 9, 10, 44, -1, 2, 26, 1, -2, 0.5)
>>> def f1(z, *params):
...     x, y = z
...     a, b, c, d, e, f, g, h, i, j, k, l, scale = params
...     return (a * x**2 + b * x * y + c * y**2 + d*x + e*y + f)
>>>
>>> def f2(z, *params):
...     x, y = z
...     a, b, c, d, e, f, g, h, i, j, k, l, scale = params
...     return (-g*np.exp(-((x-h)**2 + (y-i)**2) / scale))
>>>
>>> def f3(z, *params):
...     x, y = z
...     a, b, c, d, e, f, g, h, i, j, k, l, scale = params
...     return (-j*np.exp(-((x-k)**2 + (y-l)**2) / scale))
>>>
>>> def f(z, *params):
...     return f1(z, *params) + f2(z, *params) + f3(z, *params)
>>>
>>> rranges = (slice(-4, 4, 0.25), slice(-4, 4, 0.25))
>>> from scipy import optimize
>>> resbrute = optimize.brute(f, rranges, args=params, full_output=True,
...                           finish=optimize.fmin)

In [24]:
resbrute

(array([-1.05665192,  1.80834843]),
 -3.4085818767996527,
 array([[[-4.  , -4.  , -4.  , ..., -4.  , -4.  , -4.  ],
         [-3.75, -3.75, -3.75, ..., -3.75, -3.75, -3.75],
         [-3.5 , -3.5 , -3.5 , ..., -3.5 , -3.5 , -3.5 ],
         ..., 
         [ 3.25,  3.25,  3.25, ...,  3.25,  3.25,  3.25],
         [ 3.5 ,  3.5 ,  3.5 , ...,  3.5 ,  3.5 ,  3.5 ],
         [ 3.75,  3.75,  3.75, ...,  3.75,  3.75,  3.75]],
 
        [[-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         ..., 
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75]]]),
 array([[ 134.        ,  119.6875    ,  106.25      , ...,   74.18749997,
           85.24999999,   97.1875    ],
        [ 129.125     ,  115.        ,  101.75      , ...,   74.74999948,
           85.99999987